image:
  file: .gitpod.dockerfile

tasks:
  - name: Build
    before: |
      wget -q -O - \
        "https://github.com/getzola/zola/releases/download/v0.17.2/zola-v0.17.2-x86_64-unknown-linux-gnu.tar.gz" \
        | sudo tar xzf - -C /usr/local/bin
    command: >
      zola build --base-url="https://8002-${GITPOD_WORKSPACE_URL:8}" && nginx

ports:
  - port: 8002
    onOpen: open-preview
    name: Website
    description: Website Preview
    visibility: public

vscode:
  extensions:
    - emeraldwalk.RunOnSave
